# Package Overview
package_name: iris_model

# Data Files
training_data_file: iris.csv

# Variables
# The variable we are attempting to predict
target: species

pipeline_name: iris_model
pipeline_save_file: iris__model_output_v

features:      
  - sepal_length
  - sepal_width
  - petal_length
  - petal_width

species_var : species

species_mappings:
  setosa: 0
  versicolor: 1
  virginica: 2

# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# default algorithm parameters (will be optimized using optuna)
n_estimators: 20
max_depth: 5
